version: "3"

services:

    card-players-unite-database-server:

        container_name: card-players-unite-database-server
        
        image: postgres:14.1-alpine

        restart: always

        environment:

            - POSTGRES_USER=cardplayersunite

            - POSTGRES_PASSWORD=cardplayersunite

        ports:

            - "5432:5432"

        volumes: 

            - ./volume-data-postgres/database-server:/var/lib/postgresql/data
 
    card-players-unite-database-manager:

        container_name: card-players-unite-database-manager

        image: dpage/pgadmin4
        
        restart: always

        ports:
        
            - "5050:80"
            
        environment:
        
            PGADMIN_DEFAULT_EMAIL: rlmessick@gmail.com
            
            PGADMIN_DEFAULT_PASSWORD: aggiepride

        volumes:
        
            - ./volume-data-postgres/database-admin:/var/lib/pgadmin
            