version: "3"

services:

    card-players-unite-database-server:

        container_name: card-players-unite-database-server
        
        image: postgres:14.1-alpine

        restart: always
        user: root
        environment:

            - POSTGRES_USER=cardplayersunite
            - POSTGRES_DB=cardplayersunite
            - POSTGRES_PASSWORD=cardplayersunite

        ports:

            - "5432:5432"

        volumes: 

            - ./vol1ume-data-postgres/database-server:/var/lib/postgresql/data
 
    card-players-unite-database-manager:

        container_name: card-players-unite-database-manager
        user: root
        image: dpage/pgadmin4
        
        restart: always

        ports:
        
            - "5050:80"
            
        environment:
        
            PGADMIN_DEFAULT_EMAIL: fake@gmail.com
            
            PGADMIN_DEFAULT_PASSWORD: aggiepride

        volumes:
        
            - .//vol1ume-data-postgres/database-admin:/var/lib/pgadmin
            
